### ISSUE TITLE
Corrigir pasta

### ISSUE THREAD

**Issue by osmarbraz** [Cauan-Silva/ProjetoTriangulo#1]
Não ha necessidade de criar dentro do repositório ProjetoTriangulo a pasta ProjetoTriangulo.
Coloque a pasta src na raiz do repositório.
Faça isto em todos os projetos.

**Comment by Cauan-Silva** [comment]
Pastas corrigidas.

**Comment by Cauan-Silva** [comment]
Pastas corrigidas.
